name: Update Adblock Rules

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点 UTC 运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run filter_lists_merge.sh (with retry)
        run: |
          for i in {1..3}; do
            bash surge/filter_lists_merge.sh && break
            sleep 5
          done

      - name: Commit and push if changed
        run: |
          git add surge/reject.txt
          git diff --cached --quiet && echo "No changes." && exit 0
          git commit -m "Update adblock rules"
          git push
